/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Klijent;
import domen.Proizvod;
import domen.Racun;
import domen.StavkaRacuna;
import forme.model.RacunTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konst;

/**
 *
 * @author Korisnik
 */
public class FrmKlijent extends javax.swing.JFrame {

    private Racun r;
    private List<StavkaRacuna> listaZaBrisanje;
    private List<StavkaRacuna> listaZaCuvanje;
    private DateFormat df = new SimpleDateFormat("dd.MM.yyyy");

    public Racun getR() {
        return r;
    }

    public void setR(Racun r) {
        this.r = r;
    }

    public List<StavkaRacuna> getListaZaBrisanje() {
        return listaZaBrisanje;
    }

    public void setListaZaBrisanje(List<StavkaRacuna> listaZaBrisanje) {
        this.listaZaBrisanje = listaZaBrisanje;
    }

    public List<StavkaRacuna> getListaZaCuvanje() {
        return listaZaCuvanje;
    }

    public void setListaZaCuvanje(List<StavkaRacuna> listaZaCuvanje) {
        this.listaZaCuvanje = listaZaCuvanje;
    }

    /**
     * Creates new form FrmKlijent
     */
    public FrmKlijent() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnObrisi = new javax.swing.JButton();
        jtxtDatum = new javax.swing.JTextField();
        jbtnDodaj = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnPronadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStavke = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtSifra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbKlijent = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Izmena racuna"));

        jbtnObrisi.setText("Obrisi stavku");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jbtnDodaj.setText("Dodaj stavku");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj racun");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jLabel2.setText("Datum (dd.MM.yyyy):");

        jbtnPronadji.setText("Pronadji");
        jbtnPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPronadjiActionPerformed(evt);
            }
        });

        jtblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblStavke);

        jLabel1.setText("Sifra racuna:");

        jLabel3.setText("Klijent:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtSifra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnPronadji))
                            .addComponent(jcbKlijent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnObrisi))
                            .addComponent(jbtnSacuvaj))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtSifra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPronadji))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbKlijent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jbtnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvaj)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPronadjiActionPerformed
        try {
            int id = Integer.parseInt(jtxtSifra.getText());

            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konst.NADJI_RACUN);
            toz1.setParametar(id);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            TransferObjekatOdgovor too1 = Komunikacija.getInstance().primiOdgovor();
            Racun racun = (Racun) too1.getRezultat();
            this.setR(racun);

            jtxtSifra.setText(String.valueOf(racun.getRacunID()));
            jtxtDatum.setText(df.format(racun.getDatum()));
            jcbKlijent.setSelectedItem(racun.getKlijent());

            RacunTableModel model = new RacunTableModel(racun);
            jtblStavke.setModel(model);

            JComboBox jcbProizvod = new JComboBox();
            TableColumn tcProizvod = jtblStavke.getColumnModel().getColumn(0);
            tcProizvod.setCellEditor(new DefaultCellEditor(jcbProizvod));

            TransferObjekatZahtev toz2 = new TransferObjekatZahtev();
            toz2.setOperacija(Konst.VRATI_PROIZVODE);
            Komunikacija.getInstance().posaljiZahtev(toz2);
            TransferObjekatOdgovor too2 = Komunikacija.getInstance().primiOdgovor();
            List<Proizvod> listaP = (List<Proizvod>) too2.getRezultat();

            jcbProizvod.setModel(new DefaultComboBoxModel(listaP.toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno ucitavanje racuna na formu preko unete sifre!");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jbtnPronadjiActionPerformed

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        if (this.r == null) {
            JOptionPane.showMessageDialog(this, "Nije unet racun, prema toma nemoguce je uneti stavke racuna!");
            return;
        }

        RacunTableModel model = (RacunTableModel) jtblStavke.getModel();
        StavkaRacuna sr = new StavkaRacuna();
        model.dodajStavku(sr);
        this.listaZaCuvanje.add(sr);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblStavke.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali red!");
        }
        RacunTableModel model = (RacunTableModel) jtblStavke.getModel();
        StavkaRacuna sr = model.obrisiStavku(red);
        this.getListaZaBrisanje().add(sr);
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            int racunID = Integer.parseInt(jtxtSifra.getText());
            Date datum = df.parse(jtxtDatum.getText());
            Klijent k = (Klijent) jcbKlijent.getSelectedItem();

            Racun racun = new Racun(racunID, datum, k);

            RacunTableModel model = (RacunTableModel) jtblStavke.getModel();
            racun.setLista(model.vratiListu());
            racun.setListaZaBrisanje(this.getListaZaBrisanje());
            racun.setListaZaCuvanje(listaZaCuvanje);

            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konst.SACUVAJ_RACUN);
            toz.setParametar(racun);
            Komunikacija.getInstance().posaljiZahtev(toz);

            JOptionPane.showMessageDialog(this, "Racun je uspesno sacuvan!");
            this.setR(null);
            srediFormu();
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Neuspesno cuvanje racuna!");
        }

    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKlijent().setVisible(true);
            }
        });
    }

    private void srediFormu() {
        try {
            this.setTitle("[FON] Izmena racuna - klijent");
            listaZaBrisanje = new ArrayList<>();
            listaZaCuvanje = new ArrayList<>();

            jtxtSifra.setText("");
            jtxtDatum.setText("");

            RacunTableModel model = new RacunTableModel(new Racun());
            jtblStavke.setModel(model);

            JComboBox jcbProizvod = new JComboBox();
            TableColumn tcProizvod = jtblStavke.getColumnModel().getColumn(0);
            tcProizvod.setCellEditor(new DefaultCellEditor(jcbProizvod));

            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konst.VRATI_KLIJENTE);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            TransferObjekatOdgovor too1 = Komunikacija.getInstance().primiOdgovor();
            List<Klijent> listaK = (List<Klijent>) too1.getRezultat();

            jcbKlijent.setModel(new DefaultComboBoxModel(listaK.toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesna inicijalizacija forme i njenih komponenti!");
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnPronadji;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox<Klijent> jcbKlijent;
    private javax.swing.JTable jtblStavke;
    private javax.swing.JTextField jtxtDatum;
    private javax.swing.JTextField jtxtSifra;
    // End of variables declaration//GEN-END:variables
}
