/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Kandidat;
import domen.PrijemniIspit;
import domen.StudijskiProgram;
import forme.model.PrijemniIspitTableModel;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konst;

/**
 *
 * @author Korisnik
 */
public class FrmKlijent extends javax.swing.JFrame {

    /**
     * Creates new form FrmKlijent
     */
    public FrmKlijent() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jcbKandidat = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrijemniIspit = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtBrojPoena = new javax.swing.JTextField();
        jbtnUkloni = new javax.swing.JButton();
        jcbStudijskiProgram = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jbtnDodaj = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos rezultata prijemnog ispita"));

        jLabel3.setText("Broj poena:");

        jtblPrijemniIspit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblPrijemniIspit);

        jLabel1.setText("Studijski program:");

        jbtnUkloni.setText("Ukloni rezultat");
        jbtnUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUkloniActionPerformed(evt);
            }
        });

        jLabel2.setText("Kandidat:");

        jbtnDodaj.setText("Dodaj rezultat");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj rezultate prijemnog");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtBrojPoena)
                            .addComponent(jcbKandidat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcbStudijskiProgram, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnUkloni)
                        .addGap(0, 152, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbStudijskiProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcbKandidat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtBrojPoena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jbtnUkloni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvaj)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        if (!izvrsiValidaciju()) {
            return;
        }

        StudijskiProgram sp = (StudijskiProgram) jcbStudijskiProgram.getSelectedItem();
        Kandidat k = (Kandidat) jcbKandidat.getSelectedItem();
        double brojPoena = Double.parseDouble(jtxtBrojPoena.getText());

        PrijemniIspit pi = new PrijemniIspit(sp, k, brojPoena);

        PrijemniIspitTableModel model = (PrijemniIspitTableModel) jtblPrijemniIspit.getModel();
        model.dodajRed(pi);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUkloniActionPerformed
        int red = jtblPrijemniIspit.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali red!");
            return;
        }
        PrijemniIspitTableModel model = (PrijemniIspitTableModel) jtblPrijemniIspit.getModel();
        model.obrisiRed(red);
    }//GEN-LAST:event_jbtnUkloniActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            if (!izvrsiValidacijuListe()) {
                System.out.println("true/false -> " + izvrsiValidacijuListe());
                JOptionPane.showMessageDialog(this, "Isti kandidat je konkurisao za isti studijski program dvaput!");
                return;
            }

            PrijemniIspitTableModel model = (PrijemniIspitTableModel) jtblPrijemniIspit.getModel();
            List<PrijemniIspit> lista = model.vratiListu();

            for (PrijemniIspit pi : lista) {
                System.out.println(pi.getKandidat() + ", " + pi.getStudijskiProgram());
            }

            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konst.SACUVAJ_PRIJEMNI_ISPIT);
            toz.setParametar(lista);
            Komunikacija.getInstance().posaljiZahtev(toz);

            JOptionPane.showMessageDialog(this, "Uspesno sacuvana lista prijemnih ispita!");
        } catch (IOException ioex) {
            JOptionPane.showMessageDialog(this, "Neuspesno sacuvana lista prijemnih ispita!");
            ioex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKlijent().setVisible(true);
            }
        });
    }

    private void srediFormu() {
        try {
            this.setTitle("Univerzitet u Beogradu - Prijemni 2015.");

            PrijemniIspitTableModel model = new PrijemniIspitTableModel(new ArrayList<>());
            jtblPrijemniIspit.setModel(model);

            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konst.VRATI_STUDIJSKE_PROGRAME);
            Komunikacija.getInstance().posaljiZahtev(toz);
            TransferObjekatOdgovor too = Komunikacija.getInstance().primiOdgovor();
            List<StudijskiProgram> listaStudijskihPrograma = (List<StudijskiProgram>) too.getRezultat();

            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konst.VRATI_KANDIDATE);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            TransferObjekatOdgovor too1 = Komunikacija.getInstance().primiOdgovor();
            List<Kandidat> listaKandidata = (List<Kandidat>) too1.getRezultat();

            jcbStudijskiProgram.setModel(new DefaultComboBoxModel(listaStudijskihPrograma.toArray()));
            jcbKandidat.setModel(new DefaultComboBoxModel(listaKandidata.toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno ucitavanje listi na formu!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnUkloni;
    private javax.swing.JComboBox jcbKandidat;
    private javax.swing.JComboBox jcbStudijskiProgram;
    private javax.swing.JTable jtblPrijemniIspit;
    private javax.swing.JTextField jtxtBrojPoena;
    // End of variables declaration//GEN-END:variables

    private boolean izvrsiValidaciju() {
        if (jtxtBrojPoena.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Niste uneli broj poena!");
            return false;
        }

        double brojPoena;
        try {
            brojPoena = Double.parseDouble(jtxtBrojPoena.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Niste uneli broj kao broj poena!");
            return false;
        }
        if (brojPoena > 100 || brojPoena < 0) {
            JOptionPane.showMessageDialog(this, "Uneti broj poena nije u predvidjenom rasponu: [0-100]!");
            return false;
        }
        return true;
    }

    private boolean izvrsiValidacijuListe() {
        PrijemniIspitTableModel model = (PrijemniIspitTableModel) jtblPrijemniIspit.getModel();
        List<PrijemniIspit> lista = model.vratiListu();

        for (PrijemniIspit pi : lista) {
            int brojParova = 0;
            Kandidat k = pi.getKandidat();
            StudijskiProgram sp = pi.getStudijskiProgram();

            for (PrijemniIspit pi1 : lista) {
                if (pi1.getStudijskiProgram() == sp && pi1.getKandidat() == k) {
                    brojParova++;
                }
            }
            System.out.println("metoda za validaciju liste: " + brojParova);
            if (brojParova > 1) {
                return false;
            }
        }

        return true;
    }
}
