package forme;

import domen.Angazovanje;
import domen.Inzenjer;
import domen.Projekat;
import domen.VrstaProjekta;
import forme.model.AngazovanjeTableModel;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konst;

public class FrmKlijent extends javax.swing.JFrame {

    private DateFormat df = new SimpleDateFormat("dd.MM.yyyy");

    /**
     * Creates new form FrmKlijent
     */
    public FrmKlijent() {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jtxtDatumOd = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtDatumDo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jcbVrstaProjekta = new javax.swing.JComboBox();
        jbtnDodaj = new javax.swing.JButton();
        jbtnObrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAngazovanje = new javax.swing.JTable();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Naziv projekta:");

        jLabel2.setText("Datum od (dd.MM.yyyy):");

        jLabel3.setText("Datum do (dd.MM.yyyy):");

        jLabel4.setText("Vrsta projekta:");

        jbtnDodaj.setText("Dodaj angazovanje");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jbtnObrisi.setText("Obrisi angazovanje");
        jbtnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnObrisiActionPerformed(evt);
            }
        });

        jtblAngazovanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblAngazovanje);

        jbtnSacuvaj.setText("Sacuvaj projekat");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtDatumOd, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(jtxtNaziv))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDatumDo)
                            .addComponent(jcbVrstaProjekta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnDodaj)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnObrisi))
                            .addComponent(jbtnSacuvaj))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbVrstaProjekta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jbtnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvaj)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        AngazovanjeTableModel model = (AngazovanjeTableModel) jtblAngazovanje.getModel();
        Angazovanje a = new Angazovanje();
        Projekat p = new Projekat();
        p.setNaziv(jtxtNaziv.getText());
        a.setProjekat(p);
        model.dodajAngazovanje(a);
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnObrisiActionPerformed
        int red = jtblAngazovanje.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali red!");
        }
        AngazovanjeTableModel model = (AngazovanjeTableModel) jtblAngazovanje.getModel();
        model.obrisiAngazovanje(red);
    }//GEN-LAST:event_jbtnObrisiActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            if (!izvrsiValidaciju()) {
                return;
            }

            String naziv = jtxtNaziv.getText();
            Date datumOd = df.parse(jtxtDatumOd.getText());
            Date datumDo = df.parse(jtxtDatumDo.getText());
            VrstaProjekta vp = (VrstaProjekta) jcbVrstaProjekta.getSelectedItem();

            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konst.VRATI_PRIMARNI_KLJUC_PROJEKAT);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            TransferObjekatOdgovor too1 = Komunikacija.getInstance().primiOdgovor();
            int pkP = (int) too1.getRezultat();

            Projekat p = new Projekat(pkP, naziv, datumOd, datumDo, vp);

            AngazovanjeTableModel model = (AngazovanjeTableModel) jtblAngazovanje.getModel();
            List<Angazovanje> listaA = model.vratiListu();

            TransferObjekatZahtev toz2 = new TransferObjekatZahtev();
            toz2.setOperacija(Konst.VRATI_PRIMARNI_KLJUC_ANGAZOVANJE);
            Komunikacija.getInstance().posaljiZahtev(toz2);
            TransferObjekatOdgovor too2 = Komunikacija.getInstance().primiOdgovor();
            int pkA = (int) too2.getRezultat();

            for (Angazovanje a : listaA) {
                a.setProjekat(p);
                a.setAngazovanjeID(pkA);
                pkA++;
                System.out.println(a.getAngazovanjeID() + ", " + a.getInzenjer().toString() + ", " + a.getProjekat().getProjekatID() + ", " + a.getDatumAngazovanja() + "\n");
            }
            p.setLista(listaA);
            System.out.println(p.getProjekatID() + ", " + p.getNaziv() + ", " + p.getDatumOd() + ", " + p.getDatumDo() + ", " + p.getVrsta().getVrstaID());
            TransferObjekatZahtev toz3 = new TransferObjekatZahtev();
            toz3.setOperacija(Konst.SACUVAJ_PROJEKAT);
            toz3.setParametar(p);
            Komunikacija.getInstance().posaljiZahtev(toz3);
            TransferObjekatOdgovor too3 = Komunikacija.getInstance().primiOdgovor();
            if (too3.getIzuzetak() != null) {
                JOptionPane.showMessageDialog(this, "Uspesno cuvanje projekta i odgovarajucih angazovanja!");
            }
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Neuspesno cuvanje projekta i odgovarajucih angazovanja!");
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKlijent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKlijent().setVisible(true);
            }
        });
    }

    private void srediFormu() {
        try {
            this.setTitle("[FON] Unos projekta");

            AngazovanjeTableModel model = new AngazovanjeTableModel(new Projekat());
            jtblAngazovanje.setModel(model);

            JComboBox jcbInzenjer = new JComboBox();
            TableColumn tcInzenjer = jtblAngazovanje.getColumnModel().getColumn(1);
            tcInzenjer.setCellEditor(new DefaultCellEditor(jcbInzenjer));

            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konst.VRATI_VRSTE_PROJEKATA);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            TransferObjekatOdgovor too1 = Komunikacija.getInstance().primiOdgovor();
            List<VrstaProjekta> listaVP = (List<VrstaProjekta>) too1.getRezultat();

            TransferObjekatZahtev toz2 = new TransferObjekatZahtev();
            toz2.setOperacija(Konst.VRATI_INZENJERE);
            Komunikacija.getInstance().posaljiZahtev(toz2);
            TransferObjekatOdgovor too2 = Komunikacija.getInstance().primiOdgovor();
            List<Inzenjer> listaI = (List<Inzenjer>) too2.getRezultat();

            jcbVrstaProjekta.setModel(new DefaultComboBoxModel(listaVP.toArray()));
            jcbInzenjer.setModel(new DefaultComboBoxModel(listaI.toArray()));

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Neuspesno ucitavanje listi na formu!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnObrisi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbVrstaProjekta;
    private javax.swing.JTable jtblAngazovanje;
    private javax.swing.JTextField jtxtDatumDo;
    private javax.swing.JTextField jtxtDatumOd;
    private javax.swing.JTextField jtxtNaziv;
    // End of variables declaration//GEN-END:variables

    private boolean izvrsiValidaciju() {
        if (jtxtNaziv.equals("")) {
            JOptionPane.showMessageDialog(this, "Niste uneli naziv projekta!");
            return false;
        }
        if (jtxtDatumOd.equals("")) {
            JOptionPane.showMessageDialog(this, "Niste uneli datum pocetka projekta!");
            return false;
        }
        if (jtxtDatumDo.equals("")) {
            JOptionPane.showMessageDialog(this, "Niste uneli datum zavrsetka projekta!");
            return false;
        }
        AngazovanjeTableModel model = (AngazovanjeTableModel) jtblAngazovanje.getModel();
        List<Angazovanje> lista = model.vratiListu();

        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Niste uneli nijedno angazovanje!");
            return false;
        }

        for (Angazovanje a : lista) {
            if (a.getInzenjer().getInzenjerID() == 0) {
                JOptionPane.showMessageDialog(this, "Niste uneli inzenjera kod angazovanja!");
                return false;
            }
            if (a.getDatumAngazovanja() == null) {
                JOptionPane.showMessageDialog(this, "Niste uneli datum kod angazovanja!");
                return false;
            }
        }

        return true;
    }
}
