/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Brend;
import domen.Komponenta;
import domen.Konfiguracija;
import domen.StavkaKonfiguracije;
import forme.model.StavkaTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import komunikacija.Komunikacija;
import transfer.TransferObjekatOdgovor;
import transfer.TransferObjekatZahtev;
import util.Konst;

/**
 *
 * @author Korisnik
 */
public class FrmGlavna extends javax.swing.JFrame {

    private DateFormat df = new SimpleDateFormat("dd.MM.yyyy");

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        this.setTitle("[FON] Konfigurator - Septembar 2015");
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnDodaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtnGenerisi = new javax.swing.JButton();
        jtxtKonfiguracijaID = new javax.swing.JTextField();
        jbtnSacuvaj = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblStavke = new javax.swing.JTable();
        jcbBrend = new javax.swing.JComboBox();
        jbtnUkloni = new javax.swing.JButton();
        jtxtDatumIzrade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Unos konfiguracije"));

        jbtnDodaj.setText("Dodaj stavku");
        jbtnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDodajActionPerformed(evt);
            }
        });

        jLabel2.setText("Naziv:");

        jLabel1.setText("KonfiguracijaID:");

        jLabel3.setText("Datum izrade(dd.MM.yyyy):");

        jLabel4.setText("Brend:");

        jbtnGenerisi.setText("Generisi ID");
        jbtnGenerisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerisiActionPerformed(evt);
            }
        });

        jtxtKonfiguracijaID.setEditable(false);

        jbtnSacuvaj.setText("Sacuvaj konfiguraciju");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jtblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblStavke);

        jbtnUkloni.setText("Ukloni stavku");
        jbtnUkloni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUkloniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDatumIzrade)
                            .addComponent(jtxtNaziv)
                            .addComponent(jcbBrend, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxtKonfiguracijaID, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnGenerisi))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnUkloni)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnSacuvaj)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtKonfiguracijaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGenerisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtNaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtDatumIzrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbBrend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnDodaj)
                    .addComponent(jbtnUkloni))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnSacuvaj)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGenerisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerisiActionPerformed
        try {
            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konst.VRATI_PRIMARNI_KLJUC);
            Komunikacija.getInstance().posaljiZahtev(toz);
            TransferObjekatOdgovor too = Komunikacija.getInstance().primiOdgovor();
            int kljuc = (int) too.getRezultat();
            kljuc++;

            jtxtKonfiguracijaID.setText(String.valueOf(kljuc));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno ucitavanje primarnog kljuca!");
        }

    }//GEN-LAST:event_jbtnGenerisiActionPerformed

    private void jbtnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDodajActionPerformed
        StavkaTableModel model = (StavkaTableModel) jtblStavke.getModel();
        model.dodajStavku();
    }//GEN-LAST:event_jbtnDodajActionPerformed

    private void jbtnUkloniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUkloniActionPerformed
        int red = jtblStavke.getSelectedRow();
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Niste odabrali stavku!");
            return;
        }
        StavkaTableModel model = (StavkaTableModel) jtblStavke.getModel();
        model.obrisiStavku(red);
    }//GEN-LAST:event_jbtnUkloniActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        try {
            if (!izvrsiValidaciju()) {
                return;
            }

            int konfiguracijaID = Integer.parseInt(jtxtKonfiguracijaID.getText());
            String naziv = jtxtNaziv.getText();
            Date datumIzrade = df.parse(jtxtDatumIzrade.getText());
            Brend b = (Brend) jcbBrend.getSelectedItem();

            Konfiguracija k = new Konfiguracija(konfiguracijaID, naziv, datumIzrade, b);

            StavkaTableModel model = (StavkaTableModel) jtblStavke.getModel();
            k.setListaStavki(model.vratiListu());

            TransferObjekatZahtev toz = new TransferObjekatZahtev();
            toz.setOperacija(Konst.SACUVAJ_KONFIGURACIJU);
            toz.setParametar(k);
            Komunikacija.getInstance().posaljiZahtev(toz);

            JOptionPane.showMessageDialog(this, "Uspesno cuvanje konfiguracije!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno cuvanje konfiguracije!");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }

    private void srediFormu() {
        try {
            StavkaTableModel model = new StavkaTableModel(new Konfiguracija());
            jtblStavke.setModel(model);

            JComboBox jcbKomponenta = new JComboBox();
            TableColumn tcKomponenta = jtblStavke.getColumnModel().getColumn(0);
            tcKomponenta.setCellEditor(new DefaultCellEditor(jcbKomponenta));

            TransferObjekatZahtev toz1 = new TransferObjekatZahtev();
            toz1.setOperacija(Konst.VRATI_BRENDOVE);
            Komunikacija.getInstance().posaljiZahtev(toz1);
            TransferObjekatOdgovor too1 = Komunikacija.getInstance().primiOdgovor();
            List<Brend> listaBrendova = (List<Brend>) too1.getRezultat();

            TransferObjekatZahtev toz2 = new TransferObjekatZahtev();
            toz2.setOperacija(Konst.VRATI_KOMPONENTE);
            Komunikacija.getInstance().posaljiZahtev(toz2);
            TransferObjekatOdgovor too2 = Komunikacija.getInstance().primiOdgovor();
            List<Komponenta> listaKomponenti = (List<Komponenta>) too2.getRezultat();

            jcbBrend.setModel(new DefaultComboBoxModel(listaBrendova.toArray()));
            jcbKomponenta.setModel(new DefaultComboBoxModel(listaKomponenti.toArray()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Neuspesno ucitavanje listi na formu!");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnDodaj;
    private javax.swing.JButton jbtnGenerisi;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnUkloni;
    private javax.swing.JComboBox jcbBrend;
    private javax.swing.JTable jtblStavke;
    private javax.swing.JTextField jtxtDatumIzrade;
    private javax.swing.JTextField jtxtKonfiguracijaID;
    private javax.swing.JTextField jtxtNaziv;
    // End of variables declaration//GEN-END:variables

    private boolean izvrsiValidaciju() {
        int brojMaticnihPloca = 0;
        int brojProcesora = 0;
        int brojMemorjiskihModula = 0;

        StavkaTableModel model = (StavkaTableModel) jtblStavke.getModel();
        List<StavkaKonfiguracije> lista = model.vratiListu();

        for (StavkaKonfiguracije sk : lista) {
            if (sk.getKomponenta().getNaziv().equals("Maticna ploca")) {
                brojMaticnihPloca += sk.getKolicina();
            }
            if (sk.getKomponenta().getNaziv().equals("Procesor")) {
                brojProcesora += sk.getKolicina();
            }
            if (sk.getKomponenta().getNaziv().equals("Memorija")) {
                brojMemorjiskihModula += sk.getKolicina();
            }
        }

        if (brojMaticnihPloca != 1 || brojProcesora != 1 || (brojMemorjiskihModula < 1 || brojMemorjiskihModula > 4)) {
            JOptionPane.showMessageDialog(this, "Niste uneli propisnu konfiguraciju!");
            System.out.println("Broj maticnih: " + brojMaticnihPloca + "\nBrojprocesora: " + brojProcesora + "\nBroj memorijskih modula: " + brojMemorjiskihModula);
            return false;
        }
        System.out.println("Broj maticnih: " + brojMaticnihPloca + "\nBrojprocesora: " + brojProcesora + "\nBroj memorijskih modula: " + brojMemorjiskihModula);
        return true;
    }
}
